apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    k8s-app: prom-alertmanager1
    qcloud-app: prom-alertmanager1
    prom-app: alertmanager
  name: prom-alertmanager1
  namespace: biz-test
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: prom-alertmanager1
      qcloud-app: prom-alertmanager1
      prom-app: alertmanager
  serviceName: ""
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: prom-alertmanager1
        qcloud-app: prom-alertmanager1
        prom-app: alertmanager
    spec:
      containers:
        - args:
            - --config.file=/etc/alertmanager/alertmanager.yaml
            - --storage.path=/alertmanager
            - --web.listen-address=0.0.0.0:9093
            - --cluster.listen-address=0.0.0.0:9094
            - --cluster.peer=prom-alertmanager2:9094
          image: docker.io/1expose11/alertmanager:v0.18.0
          imagePullPolicy: IfNotPresent
          name: prom-alertmanager1
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/alertmanager/
              name: rainbow-config-out
            - mountPath: /alertmanager
              name: prom-alertmanager1
        - image: abc.com/biz-test/prometheus_rainbow:v0.0.1
          imagePullPolicy: Always
          name: rainbow
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/prome/config_out/prod
              name: rainbow-config-out
        - image: docker.io/11expose11/webhook:v0.0.1
          imagePullPolicy: IfNotPresent
          name: webhook
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: rainbow-config-out
        - name: prom-alertmanager1
          secret:
            defaultMode: 420
            secretName: prom-alertmanager1
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        annotations:
          storageclass.beta.kubernetes.io/is-default-class: cbs
        creationTimestamp: null
        name: prom-alertmanager1
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: cbs
        volumeMode: Filesystem

---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    k8s-app: prom-alertmanager2
    qcloud-app: prom-alertmanager2
    prom-app: alertmanager
  name: prom-alertmanager2
  namespace: biz-test
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: prom-alertmanager2
      qcloud-app: prom-alertmanager2
      prom-app: alertmanager
  serviceName: ""
  template:
    metadata:
      labels:
        k8s-app: prom-alertmanager2
        qcloud-app: prom-alertmanager2
        prom-app: alertmanager
    spec:
      containers:
        - image: docker.io/1expose11/alertmanager:v0.18.0
          args:
            - --config.file=/etc/alertmanager/alertmanager.yaml
            - --storage.path=/alertmanager
            - --web.listen-address=0.0.0.0:9093
            - --cluster.listen-address=0.0.0.0:9094
            - --cluster.peer=prom-alertmanager1:9094
          imagePullPolicy: IfNotPresent
          name: prom-alertmanager2
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/alertmanager/
              name: rainbow-config-out
            - mountPath: /alertmanager
              name: prom-alertmanager2
        - image: abc.com/biz-test/prometheus_rainbow:v0.0.1
          imagePullPolicy: Always
          name: rainbow
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/prome/config_out/prod
              name: rainbow-config-out
        - image: docker.io/11expose11/webhook:v0.0.1
          imagePullPolicy: IfNotPresent
          name: webhook
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: rainbow-config-out
        - name: prom-alertmanager2
          secret:
            defaultMode: 420
            secretName: prom-alertmanager2
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        annotations:
          storageclass.beta.kubernetes.io/is-default-class: cbs
        creationTimestamp: null
        name: prom-alertmanager2
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: cbs
        volumeMode: Filesystem

---
apiVersion: v1
kind: Service
metadata:
  name: prom-alertmanager1
  namespace: biz-test
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: 9093-9093-tcp
      port: 9093
      protocol: TCP
      targetPort: 9093
    - name: 9094-9094-tcp-3dateo4zsle
      port: 9094
      protocol: TCP
      targetPort: 9094
  selector:
    k8s-app: prom-alertmanager1
    qcloud-app: prom-alertmanager1
  sessionAffinity: None
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: prom-alertmanager2
  namespace: biz-test
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: 9093-9093-tcp
      port: 9093
      protocol: TCP
      targetPort: 9093
    - name: 9094-9094-tcp-3hsn922676c
      port: 9094
      protocol: TCP
      targetPort: 9094
  selector:
    k8s-app: prom-alertmanager2
    qcloud-app: prom-alertmanager2
  sessionAffinity: None
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: prom-alertmanager
  namespace: biz-test
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: 9093-9093-tcp
      port: 9093
      protocol: TCP
      targetPort: 9093
    - name: 9094-9094-tcp
      port: 9094
      protocol: TCP
      targetPort: 9094
  selector:
    prom-app: alertmanager
  sessionAffinity: None
  type: NodePort
