apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: grafana-mongodb-proxy-crm
    qcloud-app: grafana-mongodb-proxy-crm
  name: grafana-mongodb-proxy-crm
  namespace: nmpc-production
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: grafana-mongodb-proxy-crm
      qcloud-app: grafana-mongodb-proxy-crm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: grafana-mongodb-proxy-crm
        qcloud-app: grafana-mongodb-proxy-crm
    spec:
      containers:
        - image: docker.io/11expose11/mongodb-grafana:0.0.1
          imagePullPolicy: IfNotPresent
          name: grafana-mongodb-proxy-crm
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-mongodb-proxy-crm
  namespace: nmpc-production
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: 3333-3333-tcp
      port: 3333
      protocol: TCP
      targetPort: 3333
  selector:
    k8s-app: grafana-mongodb-proxy-crm
    qcloud-app: grafana-mongodb-proxy-crm
  sessionAffinity: None
  type: NodePort
