apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: prom-thanos-query
    qcloud-app: prom-thanos-query
  name: prom-thanos-query
  namespace: nmpc-production
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: prom-thanos-query
      qcloud-app: prom-thanos-query
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: prom-thanos-query
        qcloud-app: prom-thanos-query
    spec:
      containers:
        - args:
            - query
            - --http-address=0.0.0.0:9090
            - --grpc-address=0.0.0.0:10901
            - --query.partial-response
            - --query.replica-label=prometheus_replica
            - --store=prometheus-0.prometheus.$(NAMESPACE).svc.cluster.local:10901
            - --store=prometheus-1.prometheus.$(NAMESPACE).svc.cluster.local:10901
            - --store=prom-thanos-store-0.prom-thanos-store.$(NAMESPACE).svc.cluster.local:10901
            - --store=prom-thanos-store-1.prom-thanos-store.$(NAMESPACE).svc.cluster.local:10901
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/11expose11/thanos:v0.14.0
          imagePullPolicy: IfNotPresent
          name: thanos-query
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: prom-thanos-query
  namespace: nmpc-production
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: 19192-19192-tcp
      port: 10901
      protocol: TCP
      targetPort: 10901
    - name: 19092-19092-tcp
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    k8s-app: prom-thanos-query
    qcloud-app: prom-thanos-query
  sessionAffinity: None
  type: NodePort
