global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: webhook

  routes:
    - match:
        job: "test"
      receiver: callback

receivers:
  - name: "webhook"
    webhook_configs:
      - url: "http://127.0.0.1:5001"

  - name: "callback"
    webhook_configs:
      - url: "http://127.0.0.1:8080/v1/alert"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "job"]
