{
 "title": "unify容器",
 "description": "cadvisor:v0.32.0",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "数据源", "query": "prometheus" },
   {
    "name": "zone",
    "label": "实例",
    "query": "label_values(container_last_seen{job=\"container-unify\"},alias)"
   },
   {
    "name": "campus",
    "label": "园区",
    "query": "label_values( container_last_seen{job=\"container-unify\",alias=~\"$zone\"},alias)"
   },
   {
    "name": "instance",
    "label": "实例",
    "query": "label_values( container_last_seen{job=\"container-unify\",alias=~\"$zone\"},instance)"
   },
   {
    "name": "name",
    "label": "进程",
    "query": "label_values( container_last_seen{job=\"container-unify\",instance=~\"$instance\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Containers Number",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$instance\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Crash Containers Number",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{alias=~\".*$campus.*\",instance=~\"$instance\",image!=\"\"} offset 5m) - \n count(container_last_seen{alias=~\".*$campus.*\",instance=~\"$instance\",image!=\"\"}) "
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_rss{alias=~\".*$campus.*\",instance=~\"$instance\",image!=\"\",name=~\"$name\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{alias=~\".*$campus.*\",instance=~\"$instance\",image!=\"\",name=~\"$name\"}[2m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{alias=~\".*$campus.*\",instance=~\"$instance\",image!=\"\",name=~\"$name\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{alias=~\".*$campus.*\",instance=~\"$instance\",image!=\"\",name=~\"$name\"}",
     "legendFormat": "{{name}} memory limit"
    }
   ]
  }
 ]
}