{
 "title": "Kafka",
 "description": "Default Strimzi Kafka Exporter - Kafka topics and consumer groups",
 "tags": [
  "Kafka",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "prometheus", "query": "prometheus" },
   {
    "name": "alias",
    "label": "业务",
    "query": "label_values(kafka_brokers,alias)"
   },
   {
    "name": "addr",
    "label": "实例",
    "query": "label_values(kafka_brokers{alias=\"$alias\"},addr)"
   },
   {
    "name": "consumergroup",
    "label": "消费组",
    "query": "label_values(kafka_consumergroup_current_offset{addr=\"$addr\"}, consumergroup)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_consumergroup_lag{addr=\"$addr\"}, topic)"
   },
   {
    "name": "grouptopic",
    "label": "提示(group关联Topic)",
    "query": "label_values(kafka_consumergroup_lag{addr=\"$addr\",consumergroup=\"$consumergroup\"}, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "brokers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_brokers{addr=\"$addr\"}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{addr=\"$addr\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{addr=\"$addr\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{addr=\"$addr\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "In Sync Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{addr=\"$addr\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{addr=\"$addr\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions not on preferred node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_topic_partition_leader_is_preferred{addr=\"$addr\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Number of Partitions",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{addr=\"$addr\",topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{addr=\"$addr\",topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages consumed per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{addr=\"$addr\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"}[5m])/300) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Consumer Group Lag ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{addr=\"$addr\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (consumergroup,topic) "
    }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{addr=\"$addr\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (consumergroup,partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Current Offsets",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{addr=\"$addr\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (consumergroup,partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } }
 ]
}