{
 "title": "监控运营",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "自研交换机容器监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "监控园区",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum by (alias) (prometheus_build_info{selfzone=~\".*prometheus-federate-campus\"}))"
    }
   ]
  },
  {
   "title": "监控园区情况",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum by (alias) (prometheus_build_info{selfzone=~\".*prometheus-federate-campus\"})",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "监控设备情况",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum by (alias) (cadvisor_version_info{selfzone=~\".*prometheus-federate-campus\"})",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "园区Prometheus情况",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (alias,instance) (prometheus_build_info{selfzone=~\".*prometheus-federate-campus\"})",
     "legendFormat": "{{ alias }} {{ instance}}"
    }
   ]
  },
  {
   "title": "监控园区模块",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum by (alias) (cadvisor_version_info{selfzone=~\".*prometheus-federate-campus\"}))"
    }
   ]
  },
  {
   "title": "监控设备",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sum by (alias) (cadvisor_version_info{selfzone=~\".*prometheus-federate-campus\"}))"
    }
   ]
  },
  { "title": "汇总信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Mongo",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"mongodb\"})"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(mysql_up)" }
   ]
  },
  {
   "title": "Kafka",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_brokers{job=\"kafka\"}) - 1 "
    }
   ]
  },
  {
   "title": "自研交换机容器",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"self_switch_container\",instance=~\".*8081\"})"
    }
   ]
  },
  {
   "title": "已接入监控对象",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum (up) by (job)", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Unify容器",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"container-unify\"})"
    }
   ]
  },
  {
   "title": "骨干网控制器容器",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{alias=\"container_sdncontroller\",job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "骨干网控制器主机",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_exporter_build_info{alias=\"node_sdncontroller\"})"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (addr) (redis_up{job=\"redis\"}))"
    }
   ]
  },
  {
   "title": "业务",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"business\"})"
    }
   ]
  }
 ]
}