{
 "title": "Redis",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "label", "label": "业务", "query": "label_values(redis_up,label)" },
   {
    "name": "addr",
    "label": "实例",
    "query": "label_values(redis_up{label=\"$label\"}, addr)"
   },
   {
    "name": "node",
    "label": "分片",
    "query": "label_values(redis_up{addr=\"$addr\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": " max(max_over_time(redis_uptime_in_seconds{addr=\"$addr\",node=~\"$node\"}[2m])) "
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (label) (redis_connected_clients{addr=\"$addr\",node=~\"$node\"}) "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "Redis2.8主从版的没有此指标",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum by (label) (redis_memory_used_bytes{addr=\"$addr\",node=~\"$node\"})  / sum by (label) (redis_memory_max_bytes{addr=\"$addr\",node=~\"$node\"})) * 100"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_processed_total{addr=\"$addr\"}[2m]))",
     "legendFormat": "exec"
    },
    {
     "expr": "sum(irate(redis_commands_processed_total{addr=\"$addr\",node=~\"$node\"}[2m])) by (node)",
     "legendFormat": "exec_{{ node }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{addr=\"$addr\",node=~\"$node\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(redis_memory_max_bytes{addr=\"$addr\",node=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "redis_memory_used_bytes{addr=\"$addr\",node=~\"$node\"} ",
     "legendFormat": "used _{{node }}"
    },
    {
     "expr": "redis_memory_max_bytes{addr=\"$addr\",node=~\"$node\"}",
     "legendFormat": "max_{{node }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_keyspace_hits_total{addr=\"$addr\"}[2m]))",
     "legendFormat": "hit"
    },
    {
     "expr": "sum(irate(redis_keyspace_misses_total{addr=\"$addr\"}[2m]))",
     "legendFormat": "miss"
    },
    {
     "expr": "irate(redis_keyspace_hits_total{addr=\"$addr\",node=~\"$node\"}[2m])",
     "legendFormat": "hit_{{node}}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{addr=\"$addr\",node=~\"$node\"}[2m])",
     "legendFormat": "miss_{{node}}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=\"$addr\",node=~\"$node\"}) by (db,addr)",
     "legendFormat": "{{ db }}"
    },
    {
     "expr": "sum (redis_db_keys{addr=\"$addr\",node=~\"$node\"}) by (db,alias,addr,node)",
     "legendFormat": "{{db}}_{{node}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{addr=\"$addr\"}[5m]))",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "sum(rate(redis_net_output_bytes_total{addr=\"$addr\"}[5m]))",
     "legendFormat": "{{ output }}"
    },
    {
     "expr": "rate(redis_net_input_bytes_total{addr=\"$addr\",node=~\"$node\"}[5m])",
     "legendFormat": "{{ input }}_{{ node }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{addr=\"$addr\",node=~\"$node\"}[5m])",
     "legendFormat": "{{ output }}_{{ node }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=\"$addr\"}[2m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=\"$addr\"}[2m])) by (addr)",
     "legendFormat": "evicted"
    },
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=\"$addr\",node=~\"$node\"}[2m])) by (addr,node)",
     "legendFormat": "expired_{{node}}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=\"$addr\",node=~\"$node\"}[2m])) by (addr,node)",
     "legendFormat": "evicted_{{node}}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys_expiring{addr=\"$addr\",node=~\"$node\"}) by (addr)",
     "legendFormat": "expiring_key"
    },
    {
     "expr": "sum (redis_db_keys{addr=\"$addr\",node=~\"$node\"}) by (addr) - sum (redis_db_keys_expiring{addr=\"$addr\",node=~\"$node\"}) by (addr)",
     "legendFormat": "not_expiring_key"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=\"$addr\",node=~\"$node\"}) by (addr,node)",
     "legendFormat": "expiring_key_{{node}}"
    },
    {
     "expr": "sum (redis_db_keys{addr=\"$addr\",node=~\"$node\"}) by (addr,node) - sum (redis_db_keys_expiring{addr=\"$addr\",node=~\"$node\"}) by (addr,node)",
     "legendFormat": "not_expiring_key_{{node}}"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_commands_duration_seconds_total{addr=\"$addr\"}) by (cmd,label)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}